server:
  port: 8083
#  servlet:
#    context-path: /upload-server
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password:
  servlet:
    multipart:
      #限制上传文件的最大限制为15MB
      max-file-size: 15MB

mybatis:
  type-aliases-package: cn.blctek.upload.pojo
  mapper-locations: mybatis/mapper/*Mapper.xml